### ISSUE TITLE
AMO评论详细补充一下

### ISSUE THREAD

**Issue by wenketel** [Xenofex/autoproxy-plus#1]
![a8996b54gw1egarnsgqsog208v08b77y](https://cloud.githubusercontent.com/assets/5901157/2940855/f8725c34-d990-11e3-8584-6a82fc165a50.gif)

一个就是设置点了没有反应，如图所示。
![baidushurufa_2014-5-12_12-47-33](https://cloud.githubusercontent.com/assets/5901157/2940857/09f7e9c4-d991-11e3-9080-38be5412261a.png)

另一个就是设置代理主机和端口，莫非在我点了没有反应的设置面板里面？

**Comment by Xenofex** [comment]
@wenketel 你好。你这个现象很奇怪。你点击所有按钮均没有反应，应该是因为，这个小窗口界面所需要的js没有载入所致。Mozilla审核和文档都不怎么规范，我提交了几次都是因为各种原因外部js库不在白名单，不合法，最后决定把依赖的semantic.js和handlebars.js放成链接的形式。

后来Mozilla审核员又告诉我可以包含第三方js库，只要在提交审核时候说明出处，以及在项目里的文件就可以了。

目前我还在等待审核0.1.2。下个版本加上看看能否令上述两个依赖内置。

此外，外部js没有载入的原因，不知道是不是因为你没有自己设置DNS服务器的缘故。那两个文件的链接是放在cdnjs上面。虽然这个网站没有被墙，但也可能你的默认DNS无法解析。当然我不能希望用户都去手动设置DNS，我只是猜测原因。请问你有手动设置DNS吗？

感谢你的回复。

**Comment by wenketel** [comment]
@Xenofex 
http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/javascript/semantic.min.js
http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.min.js

我知道了，我同时使用了RequestPolicy扩展，所以外部js的请求被拦截了，cloudflare.com加到白名单就好了，感谢作者。
这个扩展的设置界面感觉做的很华丽的样子。
顺便问一下，这个js厍会被下载到哪里？缓存吗？

**Comment by Xenofex** [comment]
@wenketel 就是普通的http缓存，就跟你网页上下载的图片什么的一样，是浏览器自动管理的。

这个设置界面是semantic ui，是个不错的框架。当时做这个估计至少40%时间用于学这个了。其实就相当于自习了
